<a href="https://colab.research.google.com/github/Meghanakm-24/Meghanakm-24/blob/main/Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A=12
B=20
B=A
print(B)

12


In [ ]:
Class="Python batch"

In [ ]:
Class.lower()

'python batch'

In [ ]:
Class.upper()

'PYTHON BATCH'

In [ ]:
Class.title()

'Python Batch'

In [ ]:
Class.capitalize()

'Python batch'

In [ ]:
Class.swapcase()

'pYTHON BATCH'

In [ ]:
Class.isalpha()

False

In [ ]:
Class.isalnum()

False

In [ ]:
X=15
print(X)
type(X)

15


int

In [ ]:
Class="Python batch"

In [ ]:
Class.startswith("P")

True

In [ ]:
X=int(input("Enter value of X"))

create a tuple with values (10,20,30),and 2nd tuple with values(40,50,60) and concatinate the two tuples and store it in t_combine.

In [ ]:
A=(10,20,30)
B=(40,50,60)
t_combine= A+B
print(t_combine)

(10, 20, '30', 40, 50, 60)


Access the third element from t_combine.

In [ ]:
t_combine[2]

'30'

Access the first three elments from t_combine.

In [ ]:
t_combine[0:3]

(10, 20, '30')

Acces the last elements from t_combine.

In [ ]:
t_combine[3:]

(40, 50, 60)

Create a list my_list with elements
a. First element is a tuple with values 1,2,3.
b. Second element is a tuple with values "a","b","c".
c. Third element is a tuple with with values True ,False.

In [ ]:
my_list=[(1,2,3),
        ("a","b","c"),
        (True,False)]

Append a new tuple (1,'a',True) to my_list.

In [ ]:
my_list.append((1,'a',True))

In [ ]:
print(my_list)

[(1, 2, 3), ('a', 'b', 'c'), (True, False), (1, 'a', True)]


Append a new list "sparta,123 to my_list.

In [ ]:
my_list.append(["sparta", 123])

In [ ]:
print(my_list)

[(1, 2, 3), ('a', 'b', 'c'), (True, False), (1, 'a', True), ['sparta', 123]]


Create a dictionary 'Fruit' where
a. The first key is 'Fruit' and the values are("Apple","Banana","Mango","Guava")
b. The second key is 'Cost' and the vaules are(85,54,120,70)
c. Exteract all the keys from 'Fruit'
d. Extract all the keys from 'cost'.

In [ ]:
Fruits={"Apple":85,"Banana":54,"Mango":120,"Guava":70}

In [ ]:
print(Fruits.keys)

<built-in method keys of dict object at 0x7823e461d940>


In [ ]:
Fruits["Apple"]

85

Create a set named 'my_set with values(1,1,"a","a",True,True) and print the result.

In [ ]:
my_set={1,1,"a","a",True,True}

In [ ]:
print(my_set)

{1, 'a'}


Input the values of a and b as 10 and 20 respectively.Now check if a is greater or b is greater.using if condition.

In [ ]:
a=10
b=20
if a<b:
 print("bis greater")


bis greater


Take three user inputs and print the greatest number from inputs using if-else condition

In [ ]:
a=int(input("enter the valu4e of a"))
b=int(input("enter the value of b"))
c=int(input("enter the value of c"))
if a>b and a>c:
  print("a is greater")
elif b>a and b>c:
   print("b is greater")
else:
  print("c is greater")

enter the valu4e of a12
enter the value of b27
enter the value of c50
c is greater


Assignment 3

Create a list named ‘myList’ that has the following elements: 10, 20, 30,
‘apple’, True, 8.10:
a. Now in the ‘myList’, append these values: 30, 40
b.After that, reverse the elements of the ‘myList’ and store that in
‘reversedList’


In [ ]:
mylist=[10,20,30,'apple',True,8.10]

In [ ]:
mylist.append(30)
mylist.append(40)
print(mylist)

[10, 20, 30, 'apple', True, 8.1, 30, 40, 30, 40]


In [ ]:
Reversedlist=mylist[::-1]
print(Reversedlist)

[40, 30, 40, 30, 8.1, True, 'apple', 30, 20, 10]


2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,
‘information’ and ‘text’:
a. After that, eliminate the ‘text’ value from the dictionary
b. Add ‘features’ in the dictionary
c. Fetch the ‘data’ element from the dictionary and display it in the output

In [ ]:
dic={1:'data',2:'information',3:'text'}

In [ ]:
dic.pop(3)

'text'

3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.
4. Create another tuple named numeric_tuple consisting of only integer
values 10, 20, 30, 40, 50:
a. Find the minimum value from the numeric_tuple
b. Concatenate my_tuple with numeric_tuple and store the result in r1
c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’

In [ ]:
my_tuple=(1,2,3,'apple','mango')

In [ ]:
numeric_tuple=(10,20,30,40,50)

In [ ]:
min(numeric_tuple)

10

In [ ]:
r1=my_tuple+numeric_tuple
print(r1)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [ ]:
newdupli=my_tuple*2
print(newdupli)

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


5. Create 2 sets with the names set1 and set2, where set1 contains
{1,2,3,4,5} and set2 contains {2,3,7,6,1}
Perform the below operation:

a. set1 union set2

b. set1 intersection set2

c. set1 difference set2

In [ ]:
set1={1,2,3,4,5}
set2={2,3,7,6,1}

In [ ]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
set1.intersection(set2)

{1, 2, 3}

In [ ]:
set1.difference(set2)

{4, 5}

1. Create a 3x3 matrix array with values ranging from 2 to 10.


In [ ]:
import numpy as np
a=np.random.randint(2,10,(3,3))
print(a)

[[8 4 5]
 [6 3 4]
 [4 9 5]]


2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [ ]:
array=int(input("enter the value of array"))
array=array.split()

enter the value of array1 2 3 4


ValueError: invalid literal for int() with base 10: '1 2 3 4'

3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]


In [ ]:
original_array=np.array([10,20,30])
new_array=[40,50,50,70,80,90]

In [ ]:
np.append(original_array,new_array)

array([10, 20, 30, 40, 50, 50, 70, 80, 90])

4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.

In [ ]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[5,7,9],[4,7,8]])
sum_array=a1+a2
print(sum_array)

[[ 6  9 12]
 [ 6 10 12]]


5.Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
a. Extract the 1st row from the array
b. Extract the last element from the array

In [ ]:
array1=np.arange(10,91,10)
array1.shape=(3,3)
print(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
array1[0]

array([10, 20, 30])

In [ ]:
array1[2: ,0 :]

array([[70, 80, 90]])