<a href="https://colab.research.google.com/github/Meghanakm-24/Python-files/blob/main/Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A=12
B=20
B=A
print(B)

12


In [ ]:
Class="Python batch"

In [ ]:
Class.lower()

'python batch'

In [ ]:
Class.upper()

'PYTHON BATCH'

In [ ]:
Class.title()

'Python Batch'

In [ ]:
Class.capitalize()

'Python batch'

In [ ]:
Class.swapcase()

'pYTHON BATCH'

In [ ]:
Class.isalpha()

False

In [ ]:
Class.isalnum()

False

In [ ]:
X=15
print(X)
type(X)

15


int

In [ ]:
Class="Python batch"

In [ ]:
Class.startswith("P")

True

In [ ]:
X=int(input("Enter value of X"))

create a tuple with values (10,20,30),and 2nd tuple with values(40,50,60) and concatinate the two tuples and store it in t_combine.

In [ ]:
A=(10,20,30)
B=(40,50,60)
t_combine= A+B
print(t_combine)

(10, 20, '30', 40, 50, 60)


Access the third element from t_combine.

In [ ]:
t_combine[2]

'30'

Access the first three elments from t_combine.

In [ ]:
t_combine[0:3]

(10, 20, '30')

Acces the last elements from t_combine.

In [ ]:
t_combine[3:]

(40, 50, 60)

Create a list my_list with elements
a. First element is a tuple with values 1,2,3.
b. Second element is a tuple with values "a","b","c".
c. Third element is a tuple with with values True ,False.

In [ ]:
my_list=[(1,2,3),
        ("a","b","c"),
        (True,False)]

Append a new tuple (1,'a',True) to my_list.

In [ ]:
my_list.append((1,'a',True))

In [ ]:
print(my_list)

[(1, 2, 3), ('a', 'b', 'c'), (True, False), (1, 'a', True)]


Append a new list "sparta,123 to my_list.

In [ ]:
my_list.append(["sparta", 123])

In [ ]:
print(my_list)

[(1, 2, 3), ('a', 'b', 'c'), (True, False), (1, 'a', True), ['sparta', 123]]


Create a dictionary 'Fruit' where
a. The first key is 'Fruit' and the values are("Apple","Banana","Mango","Guava")
b. The second key is 'Cost' and the vaules are(85,54,120,70)
c. Exteract all the keys from 'Fruit'
d. Extract all the keys from 'cost'.

In [ ]:
Fruits={"Apple":85,"Banana":54,"Mango":120,"Guava":70}

In [ ]:
print(Fruits.keys)

<built-in method keys of dict object at 0x7823e461d940>


In [ ]:
Fruits["Apple"]

85

Create a set named 'my_set with values(1,1,"a","a",True,True) and print the result.

In [ ]:
my_set={1,1,"a","a",True,True}

In [ ]:
print(my_set)

{1, 'a'}


Input the values of a and b as 10 and 20 respectively.Now check if a is greater or b is greater.using if condition.

In [ ]:
a=10
b=20
if a<b:
 print("bis greater")


bis greater


Take three user inputs and print the greatest number from inputs using if-else condition

In [ ]:
a=int(input("enter the valu4e of a"))
b=int(input("enter the value of b"))
c=int(input("enter the value of c"))
if a>b and a>c:
  print("a is greater")
elif b>a and b>c:
   print("b is greater")
else:
  print("c is greater")

enter the valu4e of a12
enter the value of b27
enter the value of c50
c is greater


Assignment 3

Create a list named ‘myList’ that has the following elements: 10, 20, 30,
‘apple’, True, 8.10:
a. Now in the ‘myList’, append these values: 30, 40
b.After that, reverse the elements of the ‘myList’ and store that in
‘reversedList’


In [ ]:
mylist=[10,20,30,'apple',True,8.10]

In [ ]:
mylist.append(30)
mylist.append(40)
print(mylist)

[10, 20, 30, 'apple', True, 8.1, 30, 40, 30, 40]


In [ ]:
Reversedlist=mylist[::-1]
print(Reversedlist)

[40, 30, 40, 30, 8.1, True, 'apple', 30, 20, 10]


2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,
‘information’ and ‘text’:
a. After that, eliminate the ‘text’ value from the dictionary
b. Add ‘features’ in the dictionary
c. Fetch the ‘data’ element from the dictionary and display it in the output

In [ ]:
dic={1:'data',2:'information',3:'text'}

In [ ]:
dic.pop(3)

'text'

3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.
4. Create another tuple named numeric_tuple consisting of only integer
values 10, 20, 30, 40, 50:
a. Find the minimum value from the numeric_tuple
b. Concatenate my_tuple with numeric_tuple and store the result in r1
c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’

In [ ]:
my_tuple=(1,2,3,'apple','mango')

In [ ]:
numeric_tuple=(10,20,30,40,50)

In [ ]:
min(numeric_tuple)

10

In [ ]:
r1=my_tuple+numeric_tuple
print(r1)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [ ]:
newdupli=my_tuple*2
print(newdupli)

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


5. Create 2 sets with the names set1 and set2, where set1 contains
{1,2,3,4,5} and set2 contains {2,3,7,6,1}
Perform the below operation:

a. set1 union set2

b. set1 intersection set2

c. set1 difference set2

In [ ]:
set1={1,2,3,4,5}
set2={2,3,7,6,1}

In [ ]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
set1.intersection(set2)

{1, 2, 3}

In [ ]:
set1.difference(set2)

{4, 5}

1. Create a 3x3 matrix array with values ranging from 2 to 10.


In [ ]:
import numpy as np
a=np.random.randint(2,10,(3,3))
print(a)

[[8 4 5]
 [6 3 4]
 [4 9 5]]


2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [ ]:
array=int(input("enter the value of array"))
array=array.split()

enter the value of array1 2 3 4


ValueError: invalid literal for int() with base 10: '1 2 3 4'

3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]


In [ ]:
original_array=np.array([10,20,30])
new_array=[40,50,50,70,80,90]

In [ ]:
np.append(original_array,new_array)

array([10, 20, 30, 40, 50, 50, 70, 80, 90])

4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.

In [ ]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[5,7,9],[4,7,8]])
sum_array=a1+a2
print(sum_array)

[[ 6  9 12]
 [ 6 10 12]]


5.Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
a. Extract the 1st row from the array
b. Extract the last element from the array

In [ ]:
array1=np.arange(10,91,10)
array1.shape=(3,3)
print(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
array1[0]

array([10, 20, 30])

In [ ]:
array1[2: ,0 :]

array([[70, 80, 90]])

 Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return.


In [1]:
import numpy as np
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:


In [18]:
def sub_matrix(matrix,n,m):
 return [row[-m:] for row in matrix[-n:]]

In [12]:
matrix=np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
matrix[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [19]:
result=sub_matrix(matrix,2,2)
print(result)

[array([5, 6]), array([8, 9])]


Assignment 4

Create a function named ‘factor’ that can only accept 1
argument.The function should return the factorial of that
number.


In [20]:
def factor(n):
    if not isinstance(n, int) or n < 0:
        raise ValueError("Input must be a non-negative integer.")
    if n == 0 or n == 1:
        return 1
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result

In [21]:
print(factor(5))

120


Create a function named ‘check_string’, the function should accept
a string data from the user and the function should check if
the user input contains the letter ‘s’ in it. If it contains
the letter ‘s’ then print- ‘The string is containing the letter ‘s’’, if
not then print- ‘The string doesn’t contain the letter ‘s’’.

In [22]:
def check_string(user_input):
  if 's'in user_input or 'S'in user_input:
    print("The string is containing the letter 's'")
  else:
    print("The string doesn't contain the letter 's'")

In [24]:
check_string("sunshine")

The string is containing the letter 's'


Create a class named ‘student’ and inside the class, create a
function named ‘fun1’- this method should accept the user
defined input and return that value:
a. Create another method named- message() and that method
should print the user defined input that we have defined in ‘fun1’.

In [30]:
class student:
    def fun1(self):
        self.data = input("Enter something: ")
        return self.data

    def message(self):
        print("You entered:", self.data)
s1=student()
s1.fun1()
s1.message()

Enter something: hell0
You entered: hell0


Create a lambda function that should double or multiply the
number (that we will be passing in the lambda function) by 2.
Store the lambda function in a variable named ‘double_num’.


In [31]:
double_num=lambda x:x*2
print(double_num(5))

10


Take user input string and check whether that string is palindrome
or not

In [34]:
string=input("Enter a string")
cleaned_input=string.replace(" ","").lower()
if cleaned_input==cleaned_input[::-1]:
 print("The string is a palindrome")
else:
  print("The string is not a palindrome")




Enter a stringmeghana
The string is not a palindrome


Create a class named ‘Super’ and inside that class define a user-defined
function named fun1
a. Inside the ‘fun1’ function, pass the message “This is function 1 in the Super
class.” in the print statement.


In [38]:
class Super:
  def fun1(self):
   print("This function is in upper class")
obj=Super()
obj.fun1()


This function is in upper class


Create another class named ‘Modified_Super’ and inherit this class from
the Super class

a. Inside the Modified_Super class, create a function named ‘fun1’ and pass
the following message inside the print statement: ‘This is function 1 in the Modified
Super class.’

b. Create another user-defined function named ‘fun2’ and pass the
message: ‘This is the 2 nd function from the Modified Super class’ in the print
statement.

c. After that, now create an object for the Modified_Super class and call the fun1()

In [46]:
class Modified_Super(Super):
    def fun1(self):
      print("This message is modified Supee class")
    def fun2(self):
      print("This is second function from the modified Super class")
obj=Modified_Super()
obj.fun1()
obj.fun2()

This message is modified Supee class
This is second function from the modified Super class


Create 2 methods named ‘Hello’. In the 1st Hello method, pass only one
argument and pass this message: ‘This function is only having 1
argument’. And in the 2nd Hello method, pass two arguments and pass
this message: ‘This function is having 2 arguments’.
a. Try to call both the methods and analyze the output of both the methods.


In [52]:
class Myclass:
  def Hello(self,*args):
    if len(args)==1:
      print("This function is only having 1 argument")
    elif len(args)==2:
      print("This function is having 2 arguments")
    else:
      print("Invalid number of arguments")
obj1=Myclass()
obj1.Hello("Meghana")
obj1.Hello("Meghana","Maggi")

This function is only having 1 argument
This function is having 2 arguments


In [60]:
class Encapsulation:
  def __init__(self):
    self.__originalvalue=10
  def value(self):
    return self.__originalvalue
  def setvalue(self,newvalue):
    self.__originalvalue=newvalue
obj=Encapsulation()
obj.value()
obj.setvalue(25)
obj.value()

25

In [71]:
num=10
class parent_class:
    def fun1(self):
      pass
class child_class(parent_class):
     def fun2(self):
      print("The value of num is:",num)
obj=child_class()
obj.fun2()



The value of num is: 10


Create three classes named A, B and C
a. Inside the A class, create a constructor. Inside the constructor, initialize 2 global
variables name and age.

b. After initializing the global variables inside the constructor, now create a function named
‘details’ and that function should return the ‘name’ variable.

c. Inside the B class, create a constructor. Inside the constructor, initialize 2 global variables
name and id.

d. After initializing the global variables inside the constructor, now create a function named
‘details’ and that function should return the ‘name’ variable.

e. The C class should inherit from class A, and B. Inside the class C, create a
constructor, and inside the constructor, call the constructor of class A.

f. Now, create a method inside the class C, as get_details, and this function should return
the value of name.

g. Atlast, create an object of class C, and with the help of the object, call the get_details().


In [77]:
class A:
  def __init__(self):
     global name,age
     name="alice"
     age=25
  def details(self):
     return name
class B:
  def __init__(self):
     name="Sam"
     id=100
     return name
class C(A,B):
  def __init__(self):
   A.__init__(self)
  def get_details(self):
       return name
obj=C()
obj.get_details()

'alice'

Create a class named ‘Sub1’, inside the class, generate a user defined function
named ‘first’ and inside the function, pass the following statement in the print()- ‘This is
the first function from Sub 1 class’.

a. Now create another class named ‘Sub2’, and inside the class, create a function named
‘second’, and pass the following message in the print()- ‘This is the second function from
the Sub 2 class'.

b. After that, create another class named ‘Super’ and inside that class, create
a method named ‘final’, and pass the below message in the print()- ‘This is the
final method from the super class’.

c. Now, create an object for the Super class and call all the 3 user defined
methods, i.e., first(), second(), and final().


In [81]:
class Sub1:
  def first(self):
    print("This is first fun from sub1 class")
class sub2:
  def second(self):
    print("This is second fun from sub2 class")
class Super(Sub1,sub2):
  def final(self):
    print("This is final method from super class")
obj=Super()
obj.first()
obj.second()
obj.final()

This is first fun from sub1 class
This is second fun from sub2 class
This is final method from super class


Create a class named ‘Parent’, and inside the class, create a function
named ‘fun1’ and pass the following message in the print()- ‘This is the
message from the fun1’.
a. Now create a class named ‘Child1’ and inside the class, create a
method named ‘fun2’ and pass the following message in the print()- ‘This is the
message from the fun2’.

b. After that, create another class named ‘Child2’ and inside the class, create
a method named ‘fun3’ and pass the following message in the print()- ‘This is
the message from the fun3’.

c. Now, create an object of Child2 class and with the help of the object, call the
‘fun1’ method from the ‘Parent’ class.
5. Create a class named ‘Parent’, and inside the class, create a

In [82]:
class parent:
  def fun1(self):
    print("This is msg from fun1")
class child1:
  def fun2(self):
    print("This is msg from fun2")
class child2(parent):
  def fun3(self):
    print("This is msg from fun3")
obj=child2()
obj.fun1()

This is msg from fun1


In [83]:
class parent:
  def fun1(self):
    print("This is msg from fun1")
class child:
  def fun2(self):
    print("This is msg from fun2")
class Hybrid(parent,child):
  def fun3(self):
    print("This is msg from fun3")
obj=Hybrid()
obj.fun1()
obj.fun2()
obj.fun3()

This is msg from fun1
This is msg from fun2
This is msg from fun3


Assignment 5

In [84]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [88]:
import pandas as pd
filepath=('/content/drive/My Drive/Sample - Superstore.xls')
data=pd.read_excel(filepath)
print(data)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson 

From the Samplesuperstore, select only 3rd, 7th, 9th, and
20th columns and all the rows and store that in a new
DataFrame named newCols



In [90]:
newcols=data.iloc[ :,[3,7,9,20]]
print(newcols)

      Ship Date    Segment             City    Profit
0    2016-11-11   Consumer        Henderson   41.9136
1    2016-11-11   Consumer        Henderson  219.5820
2    2016-06-16  Corporate      Los Angeles    6.8714
3    2015-10-18   Consumer  Fort Lauderdale -383.0310
4    2015-10-18   Consumer  Fort Lauderdale    2.5164
...         ...        ...              ...       ...
9989 2014-01-23   Consumer            Miami    4.1028
9990 2017-03-03   Consumer       Costa Mesa   15.6332
9991 2017-03-03   Consumer       Costa Mesa   19.3932
9992 2017-03-03   Consumer       Costa Mesa   13.3200
9993 2017-05-09   Consumer      Westminster   72.9480

[9994 rows x 4 columns]


From the original DataFrame, select only the rows from the
200th index till the 1000th index(inclusive) column.
4

From the original DataFrame, select only the rows from the
200th index till the 1000th index(inclusive) column.


In [91]:
data.iloc[200:1001, :]

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
200      201  CA-2017-105074 2017-06-24 2017-06-29  Standard Class   
201      202  CA-2014-133690 2014-08-03 2014-08-05     First Class   
202      203  CA-2014-133690 2014-08-03 2014-08-05     First Class   
203      204  US-2017-116701 2017-12-17 2017-12-21    Second Class   
204      205  CA-2017-126382 2017-06-03 2017-06-07  Standard Class   
...      ...             ...        ...        ...             ...   
996      997  CA-2015-162537 2015-10-28 2015-11-03  Standard Class   
997      998  CA-2015-162537 2015-10-28 2015-11-03  Standard Class   
998      999  CA-2015-162537 2015-10-28 2015-11-03  Standard Class   
999     1000  CA-2015-162537 2015-10-28 2015-11-03  Standard Class   
1000    1001  CA-2016-155488 2016-11-13 2016-11-17  Standard Class   

     Customer ID     Customer Name      Segment        Country       City  \
200     MB-17305   Maria Bertelson     Consumer  United States      Akron   
201     BS-11755     Bruce Stewart     Consumer  United States     Denver   
202     BS-11755     Bruce Stewart     Consumer  United States     Denver   
203     LC-17140      Logan Currie     Consumer  United States     Dallas   
204     HK-14890  Heather Kirkland    Corporate  United States   Franklin   
...          ...               ...          ...            ...        ...   
996     RD-19585          Rob Dowd     Consumer  United States  Henderson   
997     RD-19585          Rob Dowd     Consumer  United States  Henderson   
998     RD-19585          Rob Dowd     Consumer  United States  Henderson   
999     RD-19585          Rob Dowd     Consumer  United States  Henderson   
1000    FM-14290      Frank Merwin  Home Office  United States  Vancouver   

      ... Postal Code   Region       Product ID         Category Sub-Category  \
200   ...       44312     East  OFF-PA-10002666  Office Supplies        Paper   
201   ...       80219     West  FUR-TA-10004289        Furniture       Tables   
202   ...       80219     West  OFF-AP-10003622  Office Supplies   Appliances   
203   ...       75220  Central  OFF-AP-10003217  Office Supplies   Appliances   
204   ...       37064    South  FUR-FU-10002960        Furniture  Furnishings   
...   ...         ...      ...              ...              ...          ...   
996   ...       42420    South  OFF-EN-10003862  Office Supplies    Envelopes   
997   ...       42420    South  OFF-ST-10004258  Office Supplies      Storage   
998   ...       42420    South  FUR-FU-10002885        Furniture  Furnishings   
999   ...       42420    South  FUR-FU-10001918        Furniture  Furnishings   
1000  ...       98661     West  OFF-AR-10002956  Office Supplies          Art   

                                           Product Name    Sales  Quantity  \
200   Southworth 25% Cotton Linen-Finish Paper & Env...   21.744         3   
201   BoxOffice By Design Rectangular and Half-Moon ...  218.750         2   
202   Bravo II Megaboss 12-Amp Hard Body Upright, Re...    2.600         1   
203                Eureka Sanitaire  Commercial Upright   66.284         2   
204          Eldon 200 Class Desk Accessories, Burgundy   35.168         7   
...                                                 ...      ...       ...   
996                  Laser & Ink Jet Business Envelopes   10.670         1   
997                          Portable Personal File Box   36.630         3   
998               Magna Visual Magnetic Picture Hangers   24.100         5   
999   C-Line Cubicle Keepers Polyproplyene Holder Wi...   33.110         7   
1000     Boston 16801 Nautilus Battery Pencil Sharpener   44.020         2   

      Discount    Profit  
200        0.2    6.7950  
201        0.5 -161.8750  
202        0.2    0.2925  
203        0.8 -178.9668  
204        0.2    9.6712  
...        ...       ...  
996        0.0    4.9082  
997        0.0    9.8901  
998        0.0    9.1580  
999        0.0   12.9129  
1000       0.0   11.4452  

[801 

Now select the rows from 20th index till 200th
index(exclusive),and columns from 2nd index till 15th index
value.


In [92]:
data.iloc[20:200,2:16]

Order Date  Ship Date       Ship Mode Customer ID       Customer Name  \
20  2014-08-27 2014-09-01    Second Class    ZD-21925  Zuschuss Donatelli   
21  2016-12-09 2016-12-13  Standard Class    KB-16585           Ken Black   
22  2016-12-09 2016-12-13  Standard Class    KB-16585           Ken Black   
23  2017-07-16 2017-07-18    Second Class    SF-20065     Sandra Flanagan   
24  2015-09-25 2015-09-30  Standard Class    EB-13870         Emily Burns   
..         ...        ...             ...         ...                 ...   
195 2014-03-21 2014-03-25  Standard Class    CB-12025   Cassandra Brandow   
196 2014-03-21 2014-03-25  Standard Class    CB-12025   Cassandra Brandow   
197 2017-11-06 2017-11-13  Standard Class    VM-21685     Valerie Mitchum   
198 2017-07-06 2017-07-13  Standard Class    FH-14365        Fred Hopkins   
199 2017-07-06 2017-07-13  Standard Class    FH-14365        Fred Hopkins   

         Segment        Country           City         State  Postal Code  \
20      Consumer  United States  San Francisco    California        94109   
21     Corporate  United States        Fremont      Nebraska        68025   
22     Corporate  United States        Fremont      Nebraska        68025   
23      Consumer  United States   Philadelphia  Pennsylvania        19140   
24      Consumer  United States           Orem          Utah        84057   
..           ...            ...            ...           ...          ...   
195     Consumer  United States       Hamilton          Ohio        45011   
196     Consumer  United States       Hamilton          Ohio        45011   
197  Home Office  United States      Westfield    New Jersey         7090   
198    Corporate  United States   Philadelphia  Pennsylvania        19120   
199    Corporate  United States   Philadelphia  Pennsylvania        19120   

      Region       Product ID         Category Sub-Category  
20      West  OFF-BI-10002215  Office Supplies      Binders  
21   Central  OFF-AR-10000246  Office Supplies          Art  
22   Central  OFF-AP-10001492  Office Supplies   Appliances  
23      East  FUR-CH-10002774        Furniture       Chairs  
24      West  FUR-TA-10000577        Furniture       Tables  
..       ...              ...              ...          ...  
195     East  OFF-AR-10004685  Office Supplies          Art  
196     East  OFF-AR-10004027  Office Supplies          Art  
197     East  OFF-ST-10001414  Office Supplies      Storage  
198     East  OFF-BI-10000343  Office Supplies      Binders  
199     East  OFF-PA-10002749  Office Supplies        Paper  

[180 rows x 14 columns]


 Display the top 100 records from the original DataFrame

In [93]:
data.head(100)

Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0        1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
1        2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
2        3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045   
3        4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
4        5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
..     ...             ...        ...        ...             ...         ...   
95      96  US-2017-109484 2017-11-06 2017-11-12  Standard Class    RB-19705   
96      97  CA-2017-161018 2017-11-09 2017-11-11    Second Class    PN-18775   
97      98  CA-2017-157833 2017-06-17 2017-06-20     First Class    KD-16345   
98      99  CA-2016-149223 2016-09-06 2016-09-11  Standard Class    ER-13855   
99     100  CA-2016-158568 2016-08-29 2016-09-02  Standard Class    RB-19465   

        Customer Name      Segment        Country             City  ...  \
0         Claire Gute     Consumer  United States        Henderson  ...   
1         Claire Gute     Consumer  United States        Henderson  ...   
2     Darrin Van Huff    Corporate  United States      Los Angeles  ...   
3      Sean O'Donnell     Consumer  United States  Fort Lauderdale  ...   
4      Sean O'Donnell     Consumer  United States  Fort Lauderdale  ...   
..                ...          ...            ...              ...  ...   
95       Roger Barcio  Home Office  United States         Portland  ...   
96     Parhena Norris  Home Office  United States    New York City  ...   
97   Katherine Ducich     Consumer  United States    San Francisco  ...   
98  Elpida Rittenbach    Corporate  United States       Saint Paul  ...   
99       Rick Bensley  Home Office  United States          Chicago  ...   

   Postal Code   Region       Product ID         Category Sub-Category  \
0        42420    South  FUR-BO-10001798        Furniture    Bookcases   
1        42420    South  FUR-CH-10000454        Furniture       Chairs   
2        90036     West  OFF-LA-10000240  Office Supplies       Labels   
3        33311    South  FUR-TA-10000577        Furniture       Tables   
4        33311    South  OFF-ST-10000760  Office Supplies      Storage   
..         ...      ...              ...              ...          ...   
95       97206     West  OFF-BI-10004738  Office Supplies      Binders   
96       10009     East  FUR-FU-10000629        Furniture  Furnishings   
97       94122     West  OFF-BI-10001721  Office Supplies      Binders   
98       55106  Central  OFF-AP-10000358  Office Supplies   Appliances   
99       60610  Central  OFF-PA-10003256  Office Supplies        Paper   

                                         Product Name     Sales  Quantity  \
0                   Bush Somerset Collection Bookcase  261.9600         2   
1   Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2   Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3       Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                      Eldon Fold 'N Roll Cart System   22.3680         2   
..                                                ...       ...       ...   
95  Flexible Leather- Look Classic Collection Ring...    5.6820         1   
96                    9-3/4 Diameter Round Wall Clock   96.5300         7   
97                     Trimflex Flexible Post Binders   51.3120         3   
98  Fellowes Basic Home/Office Series Surge Protec...   77.8800         6   
99         Avery Personal Creations Heavyweight Cards   64.6240         7   

    Discount    Profit  
0       0.00   41.9136  
1       0.00  219.5820  
2       0.00    6.8714  
3       0.45 -383.0310  
4       0.20    2.5164  
..       ...       ...  
95      0.70   -3.7880  
96      0.00   40.5426  
97      0.20   17.9592  
98      0.00   22.5852  
99      0.20   22.6184  

[100 rows x 21 columns]

Display the last 10 records from the DataFrame

In [94]:
data.tail(10)

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9984    9985  CA-2015-100251 2015-05-17 2015-05-23  Standard Class   
9985    9986  CA-2015-100251 2015-05-17 2015-05-23  Standard Class   
9986    9987  CA-2016-125794 2016-09-29 2016-10-03  Standard Class   
9987    9988  CA-2017-163629 2017-11-17 2017-11-21  Standard Class   
9988    9989  CA-2017-163629 2017-11-17 2017-11-21  Standard Class   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country         City  \
9984    DV-13465  Dianna Vittorini   Consumer  United States   Long Beach   
9985    DV-13465  Dianna Vittorini   Consumer  United States   Long Beach   
9986    ML-17410      Maris LaWare   Consumer  United States  Los Angeles   
9987    RA-19885      Ruben Ausman  Corporate  United States       Athens   
9988    RA-19885      Ruben Ausman  Corporate  United States       Athens   
9989    TB-21400  Tom Boeckenhauer   Consumer  United States        Miami   
9990    DB-13060       Dave Brooks   Consumer  United States   Costa Mesa   
9991    DB-13060       Dave Brooks   Consumer  United States   Costa Mesa   
9992    DB-13060       Dave Brooks   Consumer  United States   Costa Mesa   
9993    CC-12220      Chris Cortes   Consumer  United States  Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
9984  ...       11561    East  OFF-LA-10003766  Office Supplies       Labels   
9985  ...       11561    East  OFF-SU-10000898  Office Supplies     Supplies   
9986  ...       90008    West  TEC-AC-10003399       Technology  Accessories   
9987  ...       30605   South  TEC-AC-10001539       Technology  Accessories   
9988  ...       30605   South  TEC-PH-10004006       Technology       Phones   
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name    Sales  Quantity  \
9984                     Self-Adhesive Removable Labels   31.500        10   
9985  Acme Hot Forged Carbon Steel Scissors with Nic...   55.600         4   
9986  Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...   36.240         1   
9987  Logitech G430 Surround Sound Gaming Headset wi...   79.990         1   
9988                    Panasonic KX - TS880B Telephone  206.100         5   
9989                             Ultra Door Pull Handle   25.248         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960         2   
9991                              Aastra 57i VoIP phone  258.576         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2   

      Discount   Profit  
9984       0.0  15.1200  
9985       0.0  16.1240  
9986       0.0  15.2208  
9987       0.0  28.7964  
9988       0.0  55.6470  
9989       0.2   4.1028  
9990       0.0  15.6332  
9991       0.2  19.3932  
9992       0.0  13.3200  
9993       0.0  72.9480  

[10 rows x 21 columns]

Display the last record from the DataFrame

In [95]:
data.iloc[-1]

Row ID                                                        9994
Order ID                                            CA-2017-119914
Order Date                                     2017-05-04 00:00:00
Ship Date                                      2017-05-09 00:00:00
Ship Mode                                             Second Class
Customer ID                                               CC-12220
Customer Name                                         Chris Cortes
Segment                                                   Consumer
Country                                              United States
City                                                   Westminster
State                                                   California
Postal Code                                                  92683
Region                                                        West
Product ID                                         OFF-AP-10002684
Category                                           Office Supplies
Sub-Category                                            Appliances
Product Name     Acco 7-Outlet Masterpiece Power Center, Wihtou...
Sales                                                       243.16
Quantity                                                         2
Discount                                                       0.0
Profit                                                      72.948
Name: 9993, dtype: object

Now from the Samplesuperstore DataFrame, try to sort the data by the
tenure column according to the descending order.

In [98]:
data.sort_values(by='Sales',ascending=False)

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
2697    2698  CA-2014-145317 2014-03-18 2014-03-23  Standard Class   
6826    6827  CA-2016-118689 2016-10-02 2016-10-09  Standard Class   
8153    8154  CA-2017-140151 2017-03-23 2017-03-25     First Class   
2623    2624  CA-2017-127180 2017-10-22 2017-10-24     First Class   
4190    4191  CA-2017-166709 2017-11-17 2017-11-22  Standard Class   
...      ...             ...        ...        ...             ...   
2106    2107  US-2014-152723 2014-09-26 2014-09-26        Same Day   
4711    4712  CA-2014-112403 2014-03-31 2014-03-31        Same Day   
8658    8659  CA-2016-168361 2016-06-21 2016-06-25  Standard Class   
9292    9293  CA-2017-124114 2017-03-02 2017-03-02        Same Day   
4101    4102  US-2017-102288 2017-06-19 2017-06-23  Standard Class   

     Customer ID     Customer Name      Segment        Country           City  \
2697    SM-20320       Sean Miller  Home Office  United States   Jacksonville   
6826    TC-20980      Tamara Chand    Corporate  United States      Lafayette   
8153    RB-19360      Raymond Buch     Consumer  United States        Seattle   
2623    TA-21385      Tom Ashbrook  Home Office  United States  New York City   
4190    HL-15040      Hunter Lopez     Consumer  United States         Newark   
...          ...               ...          ...            ...            ...   
2106    HG-14965     Henry Goldwyn    Corporate  United States       Mesquite   
4711    JO-15280     Jas O'Carroll     Consumer  United States   Philadelphia   
8658    KB-16600       Ken Brennan    Corporate  United States        Chicago   
9292    RS-19765    Roland Schwarz    Corporate  United States           Waco   
4101    ZC-21910  Zuschuss Carroll     Consumer  United States        Houston   

      ... Postal Code   Region       Product ID         Category Sub-Category  \
2697  ...       32216    South  TEC-MA-10002412       Technology     Machines   
6826  ...       47905  Central  TEC-CO-10004722       Technology      Copiers   
8153  ...       98115     West  TEC-CO-10004722       Technology      Copiers   
2623  ...       10024     East  TEC-CO-10004722       Technology      Copiers   
4190  ...       19711     East  TEC-CO-10004722       Technology      Copiers   
...   ...         ...      ...              ...              ...          ...   
2106  ...       75150  Central  OFF-BI-10003460  Office Supplies      Binders   
4711  ...       19120     East  OFF-BI-10003529  Office Supplies      Binders   
8658  ...       60623  Central  OFF-BI-10003727  Office Supplies      Binders   
9292  ...       76706  Central  OFF-BI-10004022  Office Supplies      Binders   
4101  ...       77095  Central  OFF-AP-10002906  Office Supplies   Appliances   

                                           Product Name      Sales  Quantity  \
2697  Cisco TelePresence System EX90 Videoconferenci...  22638.480         6   
6826              Canon imageCLASS 2200 Advanced Copier  17499.950         5   
8153              Canon imageCLASS 2200 Advanced Copier  13999.960         4   
2623              Canon imageCLASS 2200 Advanced Copier  11199.968         4   
4190              Canon imageCLASS 2200 Advanced Copier  10499.970         3   
...                                                 ...        ...       ...   
2106                                  Acco 3-Hole Punch      0.876         1   
4711                      Avery Round Ring Poly Binders      0.852         1   
8658  Avery Durable Slant Ring Binders With Label Ho...      0.836         1   
9292           Acco Suede Grain Vinyl Round Ring Binder      0.556         1   
4101  Hoover Replacement Belt for Commercial Guardsm...      0.444         1   

      Discount     Profit  
2697       0.5 -1811.0784  
6826       0.0  8399.9760  
8153       0.0  6719.9808  
2623       0.2  3919.9888  
4190       0.0  5039.9856  
...        ...        ...  
2106       0.8    -1.4016  
4711       0.7    -0.5964  
8658  