<a href="https://colab.research.google.com/github/Meghanakm-24/Meghanakm-24/blob/main/Functions%2Cdata_types%2CNumpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
m= 10

In [ ]:
print(m)

10


In [ ]:
a =10

b =10

c =a+b

print(c)

20


Functions in python

In [ ]:
c="Data Science"

In [ ]:
c.lower()

'data science'

In [ ]:
c.upper()

'DATA SCIENCE'

In [ ]:
c.title()

'Data Science'

In [ ]:
c.capitalize()

'Data science'

In [ ]:
c.isalnum()

False

In [ ]:
c.isalpha()

False

In [ ]:
c.endswith("e")

True

In [ ]:
c.swapcase()

'dATA sCIENCE'

In [ ]:
X=int(input("Enter value of X"))

Enter value of X100


In [ ]:
m=float(input("Giuve a decimal value:"))

Giuve a decimal value:25


In [ ]:
#complex=n+ij

In [ ]:
b=5+4j

In [ ]:
type(b)

complex

In [ ]:
String1='Welcome to the world of python'

In [ ]:
print(String1)
type(String1)

Welcome to the world of python


str

In [ ]:
# when there is a multi line code print in thriple coats.

In [ ]:
String3='''Im code and i live in world of
programers'''

In [ ]:
print(String3)
type(String3)

Im code and i live in world of
programers


str

In [ ]:
c.split() # split divides based on space

['Data', 'Science']

In [ ]:
a="91-8712113656"

In [ ]:
a.split("-")

['91', '8712113656']

In [ ]:
c.split("a")

['D', 't', ' Science']

In [ ]:
c.strip()

'Data Science'

In [ ]:
a= "    Data Analytics    "

In [ ]:
a.strip()

'Data Analytics'

In [ ]:
a.lstrip()

'Data Analytics'

In [ ]:
a.rstrip()

'Data Analytics'

In [ ]:
a="Data"

In [ ]:
a.center(10,"*")

'***Data***'

In [ ]:
a.rjust(10,"*")

'******Data'

In [ ]:
a.ljust(10,"*")

'Data******'

In [ ]:
a.index("a")

1

In [ ]:
"da".join("abc")

'adabdac'

In [ ]:
#Slicing of string


In [ ]:
c="Data science"

In [ ]:
c[:4]

'Data'

In [ ]:
c[0:4]

'Data'

In [ ]:
c[0:]

'Data Science'

In [ ]:
c[ : ]

'Data Science'

In [ ]:
c[0:25]

'Data Science'

In [ ]:
c[5:]

'Science'

In [ ]:
c[5:25]

'science'

In [ ]:
String="Machine Learning"

In [ ]:
String[0:2].upper()+String[8:10].upper()

'MALE'

In [ ]:
String[0:2].upper()+String[5:7].upper()+" "+String[9:12].lower()

'MANE ear'

In [ ]:
X=["Data",9,'2024.23',(3+4j),[10,20,30]]

In [ ]:
print(X)

['Data', 9, 2024.23, (3+4j), [10, 20, 30]]


In [ ]:
X[2][4:]

'.23'

In [ ]:
topics = [
    ['Math', ['Algebra', 'Calculus', 'Geometry']],
    ['Science', ['Physics', 'Chemistry', 'Biology']],
    ['Technology', ['Programming', 'Networking', 'AI']],
    ['History', ['Ancient', 'Medieval', 'Modern']],
    ['Art', ['Painting', 'Sculpture', 'Architecture']]
]


In [ ]:
topics[0][1][2][0:3].upper()+" "+topics[1][1][2][0:3].upper()+" "+topics[1][1][1][0:4].upper()

'GEO BIO CHEM'

Operators
1.Arthematic operators

In [ ]:

X=6
Y=5
addition=X+Y
print(f"Addition:{X}+{Y}={addition}")

Addition:6+5=11


In [ ]:
subtraction=X-Y
print(f"subtraction:{X}-{Y}={subtraction}")

subtraction:6-5=1


In [ ]:
Multiplication=X*Y
print(f"Multiplication:{X}*{Y}={Multiplication}")

Multiplication:6*5=30


In [ ]:
X=15
Y=4
division=X/Y
print(f"division:{X}/{Y}={division}")

division:15/4=3.75


In [ ]:
modulus=X%Y
print(f"modulus:{X}%{Y}={modulus}")

modulus:15%4=3


In [ ]:
a=6
b=3
expn=a**b
print(expn)

216


In [ ]:
expn=a**b
print(f"expn:{a}**{b}={expn}")

expn:6**3=216


In [ ]:
X=13
Y=4
floor_division=X//Y
print(f"floor_division:{X}//{Y}={floor_division}")

floor_division:13//4=3


In [ ]:
a=9
b=4
addition=a+b
subtraction=a-b
multiplication=a*b
division=a/b
modulus=a%b
expn=a**b
floor_division=a//b
print(f"addition:{a}+{b}={addition}")
print(f"subtraction:{a}-{b}={subtraction}")
print(f"multiplication:{a}*{b}={multiplication}")
print(f"division:{a}/{b}={division}")
print(f"modulus:{a}%{b}={modulus}")
print(f"expn:{a}**{b}={expn}")
print(f"floor_division:{a}//{b}={floor_division}")


addition:9+4=13
subtraction:9-4=5
multiplication:9*4=36
division:9/4=2.25
modulus:9%4=1
expn:9**4=6561
floor_division:9//4=2


Assignment operators


In [ ]:
#= assignment
X=10
print(X)

10


In [ ]:
#+= Addition Assignment
X+=3
print(X)

13


In [ ]:
#-= Subtraction Assignment
X-=3
print(X)

10


In [ ]:
#*= Multiplication Assignment
X*=3
print(X)

30


In [ ]:
# /= Division assignment
X/=3
print(X)

3.3333333333333335


In [ ]:
# **=Exponential assignment
X**=3
print(X)

37.037037037037045


In [ ]:
# //= Floor division
X//=3
print(X)

12.0


Bitwise AND operator


In [ ]:
# &= Bitwise AND Assignment:
#& is the bitwise AND operator, which compares each bit of two numbers and returns a new number.
#Each bit in the result is 1 if the corresponding bits in both operands are 1, otherwise the bit is 0.
# 1   0   0
# 1   1   1
# 0   1   0
#1    1    1
Y=6
Y &=4
print(Y)
bin(4)

4


'0b100'

In [ ]:
a=7
a &=10
print(a)
bin(a)

2


'0b10'

Bitwise OR operator


In [ ]:
X=5
X |=3
print(X)
bin(X)

7


'0b111'

In [ ]:
a=7
a |=10
print(a)
bin(a)

15


'0b1111'

Bitwise XOR

In [ ]:
X=5
X ^=3
print(X)
bin(X)

6


'0b110'

In [ ]:
a=8
a^=2
print(a)
bin(a)

10


'0b1010'

Right shift Operator- Shifts the value to right ex(1000) X>>=2 ---001000

In [ ]:
Y=10
Y >>=3
print(Y)
bin(Y)

1


'0b1'

Bitwise Left operator- shifts the value to left ex(0001) -----000100

In [ ]:
a=5
a<<=2
print(a)
bin(a)

20


'0b10100'

Convert decimal to num and num to decimal

In [ ]:
b= int('100111',2)
print(b)

39


In [ ]:
a=10
bin(a)

'0b1010'

Comparison operator

In [ ]:
x=12
y=10
x==y

False

In [ ]:
x=12
y=10
x!=y

True

In [ ]:
x=12
y=10
x<y

False

In [ ]:
x=12
y=10
x>y

True

Logical operator

In [ ]:
a=5
b=10
print(a>2 and b<15)
print(a>2 and b<8)

True
False


In [ ]:
a=5
b=10
print(a>2 or b<15)
print(a>2 or b<8)

True
True


Identity operator

In [ ]:
a=[1,2,3]
b=a
c=[1,2,3]
d=c
print(a is b)
print(c is a)
print(c is not d)

True
False
False


Cached range(-5 to 256)


```



In [ ]:
a=157
b=220
h=220
print(a is b)
print(b is h)

False
True


In [ ]:
Fruits=['apple','banana','cherry']
print('banana' in Fruits)
print('grapes'in Fruits)

True
False


In [ ]:
Fruits=['apple','banana','cherry']
print('banana' not in Fruits)
print('grapes'not in Fruits)

False
True


In [ ]:
import math

In [ ]:
math.ceil(3.1)

4

In [ ]:
math.floor(2.9)

2

In [ ]:
math.sqrt(4)

2.0

In [ ]:
math.pow(2,1/2)

1.4142135623730951

In [ ]:
math.pow(2,4)

16.0

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.trunc(2.1)

2

In [ ]:
math.fabs(-3)

3.0

In [ ]:
math.exp(2)

7.38905609893065

In [ ]:
math.log(2,3)

0.6309297535714574

In [ ]:
math.factorial(5)

120

In [ ]:
math.gcd(40,80)

40

Conditional statements

IF statements

In [ ]:
Tomato=15
if Tomato<20:
    print("Bring 1kg of tomatoes")

Bring 1kg of tomatoes


In [ ]:
X=15
if X<20:
  print("Data science")

Data science


In [ ]:
if True:
  print("Data science")

Data science


In [ ]:
X=10
if X%2==0:
    print("Data science")

Data science


In [ ]:
x=int(input())
if not((x%2==0)and(X<10)):
  print("Data Science")


10
Data Science


IF else statements

In [ ]:
X=7
if X >5:
  print("X is greater than 5")
else:
 print("X is smaller than 5")

X is greater than 5


ELIF statements

In [ ]:
Tomato=int(input("Tomatoes cost per kg:\n"))
if Tomato<40:
  print("Bring 5 kgs of Tomatoes")
elif Tomato>=50:
  print("Bring 2 kgs of Tomatoes")
else:
  print("Bring 1/2 kg of Toamtoes")

Tomatoes cost per kg:
60
Bring 2 kgs of Tomatoes


In [ ]:
X="Data science"
if "sci" in X:
  print("Data")
else:
  print("science")

Data


In [ ]:
Age=int(input())
has_permission=True
if Age>=18:
  if has_permission:
    print("Allowed")
  else:
    print("Not Allowed")
else:
  if Age>=13:
    print("Allowed with Guardian")
  else:
    print("You are not Allowed")



21
Allowed


In [ ]:
Marks=int(input())
if Marks<35:
  print("Fail")
elif Marks>=35 and Marks<=50:
  print("Grade C")
elif Marks>=50 and Marks<75:
  print("Grade B")
elif Marks>=75 and Marks<90:
  print("Grade A")
else:
  print("Grade A+")

45
Grade C


1. for Loops

A for loop is used to iterate over a sequence (such as a list, tuple, dictionary, set, or string) and execute a block of code for each item in the sequence.

In [ ]:
Word='Hello'
for letter in Word:
  print(letter)
print(Word)

H
e
l
l
o
Hello


In [ ]:
a=5
for i in range(a):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#prime number
for i in range(1,100):
  for j in range(2,i):
     if i%j==0:
        break
  else:
    print(i)

1
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [ ]:
for i in range(1,100):
    if i%2==0:
      print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [ ]:
for i in range(1,100):
  if i%2==1:
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [ ]:
for i in range(1,10,2):
 print(i)

1
3
5
7
9


In [ ]:
n=5
for i in range(n):
 for j in range(n):
  print("*",end=' ')
 print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
n=5
for i in range(n):
  for j in range(i+1):
    print("*",end=' ')
  print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
n=5
for i in range(n):
  for j in range(i,n):
    print("*",end=' ')
  print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:

n = 5
for i in range(n):
    for j in range(i, n):
        print(' ', end=' ')
    for j in range(i + 1):
        print('*', end=' ')
    print()

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [ ]:
n=5
for i in range(n):
  for j in range(i,n):
      print(' ',end=' ')
  for j in range(i+1):
      print('*',end=' ')
  print()

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [ ]:
n=5
for i in range(n):
  for j in range(i+1):
   print(' ',end=' ')
  for j in range(i,n):
    print("*",end=' ')
  print()

  * * * * * 
    * * * * 
      * * * 
        * * 
          * 


In [ ]:
n=5
for i in range(n):
  for j in range(i,n):
   print(' ',end=' ')
  for j in range(i):
   print('*',end=' ')
  for j in range(i+1):
   print('*',end=' ')
  print()



          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [ ]:

n = 5
for i in range(n):
    for j in range(i + 1):
        print(' ', end=' ')  # leading spaces
    for j in range(i, n - 1):
        print('*', end=' ')  # left half of inverted hill
    for j in range(i, n):
        print('*', end=' ')  # right half of inverted hill
    print()

  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [ ]:
n=5
for i in range(n-1):
  for j in range(i,n):
   print(' ',end=' ')
  for j in range(i):
   print('*',end=' ')
  for j in range(i+1):
   print('*',end=' ')
  print()

for i in range(n):
    for j in range(i + 1):
        print(' ', end=' ')
    for j in range(i, n - 1):
        print('*', end=' ')
    for j in range(i, n):
        print('*', end=' ')
    print()

          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [ ]:
n=5
for i in range(1,n+1):
  print(("*"*(2*i-1)).center(2* n-1))

for j in range(n-1,0,-1):
  print(("*"*(2*j-1)).center(2*n-1))

    *    
   ***   
  *****  
 ******* 
*********
 ******* 
  *****  
   ***   
    *    


In [ ]:
n=5
for i in range(n):
  for j in range(i+1):
    print('1',end=' ')
  print()


1 
1 1 
1 1 1 
1 1 1 1 
1 1 1 1 1 


In [ ]:
n=5
p=1
for i in range(n):
  for j in range(i+1):
    print(p,end=' ')
  p+=1
  print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
n=5
p=1
for i in range(n):
  for j in range(i+1):
    print(' ',end=' ')
  for j in range(i,n):
    print(p,end=' ')
  p+=1
  print()

  1 1 1 1 1 
    2 2 2 2 
      3 3 3 
        4 4 
          5 


In [ ]:
n=5
p=1
for i in range(n):
 for j in range(i,n):
   print(' ',end=' ')
 for j in range(i):
   print(p,end=' ')
 for j in range(i+1):
   print(p,end=' ')
 p+=1
 print()

          1 
        2 2 2 
      3 3 3 3 3 
    4 4 4 4 4 4 4 
  5 5 5 5 5 5 5 5 5 


In [ ]:
n=5
p=5
for i in range(n):
  for j in range(i,n):
    print(p,end=' ')
  p-=1
  print()

5 5 5 5 5 
4 4 4 4 
3 3 3 
2 2 
1 


In [ ]:
n=5
p=0
for i in range(n):
  for j in range(i+1):
    print(p,end=' ')
  p+=2
  print()

0 
2 2 
4 4 4 
6 6 6 6 
8 8 8 8 8 


In [ ]:
n=5
for i in range(n):
  for j in range(i+1):
    if(i%2==0):
       print('1',end=' ')
    else:
      print('2',end=' ')
  print()

1 
2 2 
1 1 1 
2 2 2 2 
1 1 1 1 1 


In [ ]:
Text=''' The password for entry is XyZ@2024#—don’t forget the ‘@’ or you’re locked out! Meanwhile, user_47$ is still trying to crack the code (good luck with that!). Remember: 99% of security breaches happen due to weak P@$$w0rds!"
'''

In [ ]:
for i in Text.split():
  if i.isalnum()==True:
    print(i,end=',')

The,password,for,entry,is,forget,the,or,locked,is,still,trying,to,crack,the,code,luck,with,of,security,breaches,happen,due,to,weak,

In [ ]:
X=0
for i in Text:
    if i .isupper():
      X=X+1

2. while Loops
A while loop repeats a block of code as long as a specified condition is true

In [ ]:
count=1
while count<=30:
  print(count)
  count +=2

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29


In [ ]:
a = 1
while a<10:
  if(a%2==0):
      print(a ,"is even number")
  else:
      print(a ,"is odd number")
  a+=1

1 is odd number
2 is even number
3 is odd number
4 is even number
5 is odd number
6 is even number
7 is odd number
8 is even number
9 is odd number


In [ ]:
X=2
counter=1
while X<5:
  print("Interation",counter,X)
  counter=counter+1
  X=X+1


Interation 1 2
Interation 2 3
Interation 3 4


Break

In [ ]:
for i in range(1,100):
 if i==10:
   print(i)
   break

10


In [ ]:
for i in range(1,100):
 if i==10:
    break
 print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(1,100):
  print(i)
  if i==10:
    break

1
2
3
4
5
6
7
8
9
10


Continue

In [ ]:
for i in range(1,6):
  for j in range(1,6):
    print(i,j)
    if j==3:
     break

1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3
4 1
4 2
4 3
5 1
5 2
5 3


In [ ]:
for i in range(0,10):
 if i==5:
   continue
 print(i,end=",")

0,1,2,3,4,6,7,8,9,

In [ ]:
for i in range(10):
  if i % 2==1:
    continue
  print(i,end=" ")

0 2 4 6 8 

In [ ]:
for i in range(0,10):
  if i<5:
    continue
    print(i,end=',')
  else:
    print(i,end=',')

5,6,7,8,9,

In [ ]:
for i in range(1,6):
   for j in range(1,6):
     if j==3:
      continue
     print(i,j)

1 1
1 2
1 4
1 5
2 1
2 2
2 4
2 5
3 1
3 2
3 4
3 5
4 1
4 2
4 4
4 5
5 1
5 2
5 4
5 5


In [ ]:
for i in range(1,6):
  for j in range(i):
    print(i,end=' ')
  print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


in Python functions are a fundamental concept that allows you to group a set of statements so you can run them multiple times throughout your code. Functions help make your code modular, reusable, and organized. Let's dive into the details of functions in Python and break down every aspect of them.

Defining a Function
A function is defined using the def keyword, followed by the function name, parentheses (), and a colon :. The body of the function contains the code that executes when the function is called.

In [ ]:
def greet():
  print("Hello world")

In [ ]:
greet();

Hello world


In [ ]:
def greet(arg):
  print(f"Good morning,{arg}")
greet("Students")

Good morning,Students


In [ ]:
def multiply(a,b):
  return a*b
result=multiply(3,5)
print(result)

15


In [ ]:
def division(a,b):
   return a/b
result=division(3,5)
print(result)

0.6


In [ ]:
def add(a,b):
  return a+b
def sub(m,n):
  return m-n
def div(g,f):
  return g/f
result=add(5,10)
print(result)
result=sub(5,10)
print(result)
result=div(5,10)
print(result)

15
-5
0.5


Arbitrary arguements -----To assign many numbers

In [ ]:
def add(*args):
  return sum(args)
print(add(2,3,4,5))
print(add(3,4,6,7))

14
20


In [ ]:
def average(*args):
  return mean(args)
print(average(2,3,4,5))
print(average(3,4,6,7,6))


NameError: name 'mean' is not defined

**Kwargs-----to assign keywords

In [ ]:
def print_details(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}:{value}")
print_details(name="Alice",age=25,city="New York")

name:Alice
age:25
city:New York


Lambda function

In [ ]:
add=lambda a,b:a+b
print(add(2,3))

5


In [ ]:
subtraction=lambda a,b:a-b
print(subtraction(2,3))

-1


In [ ]:
#crate a function to find square of a number
square = lambda x:x*x
print(square(2))

4


In [ ]:
cube=lambda x: x*x*x
print(cube(5))

125


Python Arrays

In [ ]:
# B--intgers ranges b/w 0 to 255
import array as arr
a=arr.array('B',[1,25,3,4,56,7])
print(a)

array('B', [1, 25, 3, 4, 56, 7])


In [ ]:
#u----single char
import array as arr
b=arr.array('u',['H','T','U'])
print(b)

array('u', 'HTU')


In [ ]:
import array as arr
x=arr.array('i',[1,2,3,4,5,6])
print(x)
x.append(8)
print(x)

array('i', [1, 2, 3, 4, 5, 6])
array('i', [1, 2, 3, 4, 5, 6, 8])


In [ ]:
x.extend([12,14,16])
print(x)

array('i', [1, 2, 3, 4, 5, 6, 8, 12, 14, 16])


In [ ]:
# it inserts values in a specified position ex (4,24) 4 represents 4th position and 24 represents value to be inserted
x.insert(4,5)
print(x)

array('i', [1, 2, 3, 4, 5, 5, 6, 8])


In [ ]:
# removes the value in the specified position(removes based on index)
x.pop(2)
print(x)

array('i', [1, 2, 24, 6, 8, 12, 14, 16])


In [ ]:
#removes first occurance of the element(removes based on occurance
x.remove(8)
print(x)


array('i', [1, 2, 24, 6, 12, 14, 16])


In [ ]:
#removes sec occurance of the values
def remove_sec_occurance(array,value):
     count=0
     for elements in range(len(array)):
       if array[elements]==value:
         count+=1
         if count==2:
            array.pop(elements)
            break
remove_sec_occurance(x,5)
print(x)


array('i', [1, 2, 3, 4, 5, 6, 8])


In [ ]:
def remove_occurance(array,value):
  count=0
  for elements in range(len(array)):
    if array[elements]==value:
      count+=1
      if count==2:
        array.pop(elements)
        break

In [ ]:
x.count(1)

1

In [ ]:
print("original array:",x)
x.reverse()
print("Reversed array:",x)

original array: array('i', [1, 2, 24, 6, 12, 14, 16])
Reversed array: array('i', [16, 14, 12, 6, 24, 2, 1])


In [ ]:
#buffer_info----memory address of elements
x.buffer_info()

(135819769070016, 7)

In [ ]:
print(x.tolist())

[16, 14, 12, 6, 24, 2, 1]


NumPy (Numerical Python)
is a powerful library for numerical computations in Python.
It provides support for arrays, matrices, and
many mathematical functions to operate on these data structures.

In [ ]:
import numpy as np
np.random.randint(0,10,6)

array([7, 2, 0, 8, 0, 6])

In [ ]:
import numpy as np
x=np.array([2,3,4,5])
print(x/2)

[1.  1.5 2.  2.5]


In [ ]:
array=np.random.randint(0,10,(3,3))

In [ ]:
array

array([[1, 6, 7],
       [2, 5, 1],
       [1, 3, 0]])

In [ ]:
np.random.randint(0,10,(2,3))

array([[1, 3, 2],
       [8, 6, 2]])

Array slicing

In [ ]:
data=np.random.randint(0,10,(5,4))
data

array([[7, 3, 4, 2],
       [5, 8, 8, 2],
       [0, 0, 6, 4],
       [6, 6, 1, 7],
       [1, 2, 5, 7]])

In [ ]:
data[1:3,1:3]

array([[8, 8],
       [0, 6]])

In [ ]:
data[2:4,1:3]

array([[0, 6],
       [6, 1]])

Dimensional arrays

In [ ]:
#Numpy

#1 D array:

import numpy as np
a=np.array([1,23,24])
a #or print(a)

array([ 1, 23, 24])

In [ ]:
#2D array
b=np.array([[1,2,3],[5,6,7],[3,6,7]])
print(b)

[[1 2 3]
 [5 6 7]
 [3 6 7]]


In [ ]:
#3D array
c=np.array([[[2,3,4],[5,6,7]],[[8,9,10],[1,2,3]]])
print(c)

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [ 1  2  3]]]


In [ ]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

function to get other values otherthan 0 and 1 is full

In [ ]:
np.full((4,4),-6)

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

To get intervals

In [ ]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

To get equal spaces or equal intervals

In [ ]:
np.linspace(10,5,4)

array([10.        ,  8.33333333,  6.66666667,  5.        ])

Gives identical matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])


In [ ]:
data

array([[ 5,  4,  0,  1],
       [11,  4, 10,  7],
       [ 7, 10,  5,  6],
       [ 7, 12, 10,  4],
       [ 3,  7,  3,  4]])

In [ ]:
data.sum()

np.int64(120)

In [ ]:
data.max()

np.int64(12)

In [ ]:
data.min()

np.int64(0)

In [ ]:
data.mean()

np.float64(6.0)

In [ ]:
b=np.array([[1,2,3],[5,6,7],[3,6,7]])
print(b.shape)

(3, 3)


In [ ]:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]])
print("original array:\n",a)
print(a.shape)
a.shape=(6,2)
print("changed array:\n",a)

original array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
(3, 4)
changed array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]


In [ ]:
import numpy as np
a=np.arange(30)
a.shape=(2,5,3)
print(a)



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size )    #9
print(a.shape)    #3,3
print(a.ndim)     #2 D
print(a.dtype)
#

9
(3, 3)
2
int64


In [ ]:
x=np.random.randint(0,20,(6,5))
print(x)

[[18  0 10  8  0]
 [17 18  4  6 16]
 [15 17  3  2 18]
 [16 18  0 12  0]
 [ 8  5  2 13 16]
 [ 7  1 19 14 16]]


In [ ]:
print(x.shape)

(6, 5)


In [ ]:
x.shape()

TypeError: 'tuple' object is not callable

In [ ]:
x.ravel()

array([18,  0, 10,  8,  0, 17, 18,  4,  6, 16, 15, 17,  3,  2, 18, 16, 18,
        0, 12,  0,  8,  5,  2, 13, 16,  7,  1, 19, 14, 16])

In [ ]:
y=x.ravel()

In [ ]:
y.reshape(10,3)

array([[18,  0, 10],
       [ 8,  0, 17],
       [18,  4,  6],
       [16, 15, 17],
       [ 3,  2, 18],
       [16, 18,  0],
       [12,  0,  8],
       [ 5,  2, 13],
       [16,  7,  1],
       [19, 14, 16]])

In [ ]:
x1=np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [ ]:
x2=np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [ ]:
np.vstack((x1,x2))

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.hstack((x1,x2))

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [ ]:
np.concatenate((x1,x2),axis=0)

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.concatenate((x1,x2),axis=1)

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

Mathematical functions

In [ ]:
#addition
x=np.array([10,2,3])
np.sum(x)

np.int64(15)

In [ ]:
array1=np.array([[1,2,3],
                  [4,5,6]])
array2=np.array([[7,8,9],
                  [10,11,12]])
sum_array=array1+array2
print("Addition:\n",sum_array)

Addition:
 [[ 8 10 12]
 [14 16 18]]


In [ ]:
#subtrction
a1=np.array([0,1,6])
a2=np.array([0,5,3])
sub_array=a1-a2
print("Subtraction:\n",sub_array)

Subtraction:
 [ 0 -4  3]


In [ ]:
#broadcasting
#addition
a=np.array([[1,2,],[6,8],[6,5]])
b=np.array([5,4])
result=a+b
print(result)

[[ 6  6]
 [11 12]
 [11  9]]


In [ ]:
#subtraction
a=np.array([[1,2,],[6,8],[6,5]])
b=np.array([5,4])
result=a-b
print(result)

[[-4 -2]
 [ 1  4]
 [ 1  1]]


Array multiplication

In [ ]:
#for multiplication there should be one row in sec array or it should have equal rows and columns to first array
array1=np.array([[1,2,3],
                  [4,5,6]])
array2=np.array([[7,8,9],
                  [10,11,12]])
mult_array=array1*array2
print("Multiplication:\n",mult_array)

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


Matrix Multiplication

In [ ]:
#the num of rows in both matrices should be same
x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))

In [ ]:
x1

array([[1, 9],
       [4, 0]])

In [ ]:
x2

array([[3, 6],
       [9, 0]])

In [ ]:
np.dot(x1,x2)

array([[84,  6],
       [12, 24]])

Division

In [ ]:
array1=np.array([[1,2,3],
                  [4,5,6]])
array2=np.array([[7,8,9],
                  [10,11,12]])
div_array=array1/array2
print("Division:\n",div_array)

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Exponent

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

String functions

In [ ]:
x=np.array(['1','2','3','data'])

In [ ]:
np.char.center(x,10,fillchar='*')

array(['****1*****', '****2*****', '****3*****', '***data***'],
      dtype='<U10')

In [ ]:
y=np.array(['1','2','3','data engineering'])

In [ ]:
print(np.char.upper(y))
print(np.char.lower(y))
print(np.char.title(y))
print(np.char.capitalize(y))

['1' '2' '3' 'DATA ENGINEERING']
['1' '2' '3' 'data engineering']
['1' '2' '3' 'Data Engineering']
['1' '2' '3' 'Data engineering']


In [ ]:
np.char.split(y,'e')

array([list(['1']), list(['2']), list(['3']),
       list(['data ', 'ngin', '', 'ring'])], dtype=object)

In [ ]:
np.char.count(y,'e')

array([0, 0, 0, 3])

In [ ]:
np.char.startswith(x,'d')

array([False, False, False,  True])

In [ ]:
np.char.endswith(x,'g')

array([False, False, False,  True])

In [ ]:
np.char.rjust(x,10,fillchar='*')

array(['*********1', '*********2', '*********3', '******data'],
      dtype='<U10')

In [ ]:
np.char.ljust(x,10,fillchar='*')

array(['1*********', '2*********', '3*********', 'data******'],
      dtype='<U10')

In [ ]:
np.char.replace(y,'a','^^')

array(['1', '2', '3', 'd^^t^^ engineering'], dtype='<U18')

In [ ]:
a=np.array([1,2,3,4,5])
print("sqrt of a:",np.sqrt(a))
print("expn of a:",np.exp(a))
print("log of a:",np.log(a))
print("sin of a:",np.sin(a))
print("cos of a:",np.cos(a))

sqrt of a: [1.         1.41421356 1.73205081 2.         2.23606798]
expn of a: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log of a: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
sin of a: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos of a: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


Aggregate functions

In [ ]:
a=np.array([1,2,3,4,5])
print("sum:",np.sum(a))
print("max:",np.max(a))
print("min:",np.min(a))
print("medain:",np.median(a))
print("mean:",np.mean(a))
print("correlation coefficient:",np.corrcoef(a))
print("standard deviation:",np.std(a))
print("variance:",np.var(a))


sum: 15
max: 5
min: 1
medain: 3.0
mean: 3.0
correlation coefficient: 1.0
standard deviation: 1.4142135623730951
variance: 2.0
